apiVersion: v1
kind: Pod
metadata:
  name: test-logger
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date) >> /var/log/app.log; sleep 5; done"]
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
      claimName: app-logs-pvc
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "app"  
      effect: "NoSchedule"
