apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_PASSWORD:c2VjdXJlcGFzc3dvcmQ=           # كلمة مرور المستخدم (base64)
  MySQL_ROOT_PASSWORD:cm9vdHBhc3MxMjM=       # كلمة مرور root (base64)
